Components
Neoris-test/arquetipo-front pull request #5
Opened 2021-12-30 18:02 UTC by Neoris-test

He hecho algunos cambios en la estructura del html por el tema del  responsive

2021-12-31 10:24 UTC, neoris-blanca requested changes
Solo algunos cambios de formato

2021-12-31 10:24 UTC, neoris-blanca commented on src/app/core/footer/footer.component.ts
> +   }
si se puede dejar en una sola línea mejor: constructor() { }

2021-12-31 10:24 UTC, neoris-blanca commented on src/app/core/footer/footer.component.ts
>    ngOnInit(): void {
Si el ngOnInit no se usa, mejor quitarlo (y quitar el implements OnInit)

2021-12-31 10:24 UTC, neoris-blanca commented on src/styles/components/_components.scss
>  .c-footer{
Si se puede dejar un espacio antes de la llave, mejor: .c-footer {

2021-12-31 10:24 UTC, neoris-blanca commented on src/styles/components/_components.scss
> +    .p-button.p-button-link:enabled{
Si se puede dejar un espacio antes de la llave, mejor: enabled {

2021-12-31 10:24 UTC, neoris-blanca commented on src/styles/components/_components.scss
> +    .p-button.p-button-link:enabled:focus{
Si se puede dejar un espacio antes de la llave, mejor: focus{

2021-12-31 10:24 UTC, neoris-blanca commented on src/styles/components/_components.scss
> +     }
Cuidado con los espacios. Mejor usar el tabulador para que todos queden igual

2021-12-31 10:24 UTC, neoris-blanca commented on src/styles/generic/_generic.scss
>  body{
Idem espacio después de body {

2021-12-31 10:24 UTC, neoris-blanca commented on src/styles/generic/_generic.scss
> +section{
Idem espacio

2021-12-31 10:24 UTC, neoris-blanca commented on src/styles/generic/_generic.scss
> +main{
Idem espacio

2021-12-31 10:24 UTC, neoris-blanca commented on src/styles/generic/_generic.scss
> +button{
Idem button espacio {

2021-12-31 10:24 UTC, neoris-blanca commented on src/styles/generic/_generic.scss
> +:host ::ng-deep .p-button{
Idem

2022-01-03 08:34 UTC, Neoris-test reviewed
Ya esta realizados los cambios que me comentaste

2022-01-03 08:34 UTC, Neoris-test commented on src/styles/components/_components.scss
>  .c-footer{
listo

2022-01-03 08:34 UTC, Neoris-test commented on src/styles/components/_components.scss
> +    .p-button.p-button-link:enabled{
listo

2022-01-03 08:34 UTC, Neoris-test commented on src/styles/components/_components.scss
> +    .p-button.p-button-link:enabled:focus{
listo

2022-01-03 08:34 UTC, Neoris-test commented on src/styles/components/_components.scss
> +     }
Los espacios estan con el tabulador pero no se si el prettier este funcionado bien

2022-01-03 08:34 UTC, Neoris-test commented on src/styles/generic/_generic.scss
>  body{
listo

2022-01-03 08:34 UTC, Neoris-test commented on src/styles/generic/_generic.scss
> +section{
listo

2022-01-03 08:34 UTC, Neoris-test commented on src/styles/generic/_generic.scss
> +button{
listo

2022-01-03 08:34 UTC, Neoris-test commented on src/styles/generic/_generic.scss
> +:host ::ng-deep .p-button{
listo

2022-01-03 08:36 UTC, merged

2022-01-03 08:36 UTC, Neoris-test commented
Realizo el merge de las ramas